<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="atreus">


  
<!--................................ XACRO CONSTANTS .............................. -->

<xacro:property name="chassis_height"                       value="0.1"/>
<xacro:property name="chassis_length"                       value="0.8"/>
<xacro:property name="chassis_width"                        value="0.6"/>
<!-- Z distance to centre of the robot -->
<xacro:property name="chassis_ground_clearance"             value="${0.1+chassis_height/2}"/>
<xacro:property name="chassis_mass"                         value="0.1"/>

<xacro:property name="wheel_mass"                           value="1"/>
<xacro:property name="wheel_radius"                         value="0.1"/>
<xacro:property name="wheel_width"                          value="0.1"/>
<xacro:property name="wheel_pos"                            value="-0.175"/>
<xacro:property name="wheel_base"                           value="${wheel_width+chassis_width}"/>
<xacro:property name="wheel_torque"                         value="10"/>

<xacro:arg      name="front_camera_enabled"                 default="true" />
<xacro:arg      name="front_camera_type"                    default="depth"/>
<xacro:property name="front_camera_baseline"                value="0.06"/>
<xacro:property name="front_camera_height"                  value="0.3"/>
<xacro:property name="front_camera_horizontal_fov"          value="60"/>

<xacro:arg      name="side_camera_enabled"                  default="true" />
<xacro:property name="side_camera_height"                   value="0.3"/>
<xacro:property name="side_camera_horizontal_fov"           value="60"/>

<xacro:arg      name="ultrasonic_enabled"                   default="true" />
<xacro:property name="ultrasonic_horizontal_samples"        value="10"/>
<xacro:property name="ultrasonic_horizontal_min_angle"      value="-15"/>  <!--Degrees-->
<xacro:property name="ultrasonic_horizontal_max_angle"      value="15"/>
<xacro:property name="ultrasonic_vertical_samples"          value="10"/>
<xacro:property name="ultrasonic_vertical_min_angle"        value="-15"/> 
<xacro:property name="ultrasonic_vertical_max_angle"        value="15"/>
<xacro:property name="ultrasonic_min_range"                 value="0.02"/>
<xacro:property name="ultrasonic_max_range"                 value="4"/>
<xacro:property name="ultrasonic_fov"                       value="17"/>   <!--Degrees-->

<xacro:arg      name="two_d_lidar_enabled"                  default="true" />
<xacro:property name="two_d_lidar_update_rate"              value="50"/>
<xacro:property name="two_d_lidar_sample_size"              value="361"/>
<xacro:property name="two_d_lidar_min_angle"                value="0"/>
<xacro:property name="two_d_lidar_max_angle"                value="360"/>
<xacro:property name="two_d_lidar_min_range"                value="0.1"/>
<xacro:property name="two_d_lidar_max_range"                value="16"/>

<xacro:arg      name="latitude"                             default="100" />
<xacro:arg      name="longitude"                            default="100" />

<xacro:arg      name="obstacle_feasibility_mode_enabled"    default="true" />
<xacro:property name="obstacle_feasibility_rod_height"      value="0.45"/>
<xacro:property name="obstacle_feasibility_plate_size"      value="0.35"/>
<xacro:property name="obstacle_feasibility_alpha"           value="45"/>  <!--Degrees-->
<xacro:property name="obstacle_feasibility_L"               value="0.2"/> <!--Sensor Separation-->
<xacro:property name="obs_ultrasonic_horizontal_samples"    value="10"/>
<xacro:property name="obs_ultrasonic_horizontal_min_angle"  value="-15"/>  <!--Degrees-->
<xacro:property name="obs_ultrasonic_horizontal_max_angle"  value="15"/>
<xacro:property name="obs_ultrasonic_vertical_samples"      value="10"/>
<xacro:property name="obs_ultrasonic_vertical_min_angle"    value="-15"/> 
<xacro:property name="obs_ultrasonic_vertical_max_angle"    value="15"/>
<xacro:property name="obs_ultrasonic_min_range"             value="0.02"/>
<xacro:property name="obs_ultrasonic_max_range"             value="4"/>
<xacro:property name="obs_ultrasonic_fov"                   value="17"/>   <!--Degrees-->


<!-- ............................... LOAD MACROS ................................. -->

<xacro:include filename="$(find atreus)/urdf/atreus.gazebo"/>
<xacro:include filename="$(find atreus)/urdf/materials.xacro"/>
<xacro:include filename="$(find atreus)/urdf/macros.xacro"/>

<!--.............................................................................. -->



<!-- ................................ BASE LINK .................................. -->

<link name="base_footprint"/>
<link name="base_link">

	<collision name='collision'>
		<origin xyz="0 0 ${chassis_ground_clearance}" rpy="0 0 0" />
  		<geometry>
    		<box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
  		</geometry>
	</collision>

	<visual>
		<origin xyz="0 0 ${chassis_ground_clearance}" rpy="0 0 0" />
  		<geometry>
    		<box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
  		</geometry>
  		<material name="blue"/>
	</visual>


	<inertial>
  		<mass value="${chassis_mass}"/>
  		<xacro:box_inertia m="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z = "${chassis_height}"/>
	</inertial>
</link>


<joint name="base_footprint_joint" type="fixed">
	<parent link="base_footprint"/>
	<child link="base_link"/>
</joint>

<gazebo reference="base_link">
   <material>Gazebo/Blue</material>
</gazebo>


<!-- ................................ WHEELS ..................................... -->

<xacro:wheel cardinality="front" dexterity="left"  fb="-1"  lr ="1" />
<xacro:wheel cardinality="front" dexterity="right" fb="-1"  lr="-1" />
<xacro:wheel cardinality="back"  dexterity="left"  fb= "1"  lr ="1" />
<xacro:wheel cardinality="back"  dexterity="right" fb= "1"  lr="-1" />


<!-- ............................ INTEL REALSENSE ................................ -->


<xacro:if value="$(arg front_camera_enabled)">

    <!-- FRONT CAMERA HOLDER -->

    <link name="front_camera_holder">

      <collision name='collision'>
        <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <box size="0.02 0.02 ${front_camera_height}"/>
          </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <box size="0.02 0.02 ${front_camera_height}"/>
          </geometry>
          <material name="red"/>
      </visual>

      <inertial>
          <mass value="0.01"/>
          <xacro:box_inertia m="0.01" x="0.02" y="0.02" z = "${front_camera_height}"/>
      </inertial>

    </link>

    <joint name="front_camera_holder_joint" type="fixed">
        <origin rpy="0 0 0" xyz="${chassis_length/4} 0 ${chassis_height/2+front_camera_height/2+chassis_ground_clearance}" />
        <parent link="base_link"/>
        <child link="front_camera_holder"/>
    </joint>

    <gazebo reference="front_camera_holder">
        <material>Gazebo/Red</material>
    </gazebo>

    <xacro:if value="$(eval front_camera_type=='depth')">

      <!-- INTEL REALSENSE CAMERA -->

        <link name="d435_camera">

            <visual>
                <origin rpy="${pi/2} 0 ${pi/2}" xyz="-0.0125 -0.0025 -0.008"/>
                <geometry>
                    <mesh filename="package://atreus/meshes/realsense/realsense.STL"/>
                </geometry>
                <material name="aluminium"/>
            </visual>

            <collision>
                <geometry>
                    <box size="0.0078 0.130 0.0192"/>
                </geometry>
            </collision>

            <inertial>
                <mass value="0.0615752"/>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <inertia ixx="9.108e-05"
                        ixy="0"
                        ixz="0"
                        iyy="2.51e-06"
                        iyz="0"
                        izz="8.931e-05"
                />
            </inertial>
        </link>

        <gazebo reference="d435_camera">
          <material>Gazebo/White</material>
        </gazebo>

        <joint name="realsense_joint" type="fixed">
            <parent link="front_camera_holder"/>
            <child link="d435_camera"/>
            <origin rpy="0 0 0" xyz="0 0 ${front_camera_height/2+0.0192/2}"/>
        </joint>

        <link name="color" />
        <link name="depth" />
        <link name="ired1" />
        <link name="ired2" />


        <joint name="color_joint" type="fixed">
            <parent link="d435_camera" />
            <child link="color" />
            <origin xyz="0 -0.046 0.004" rpy="1.5707 3.1414 1.5707"/>
        </joint>

        <joint name="depth_joint" type="fixed">
            <parent link="d435_camera" />
            <child link="depth" />
            <origin xyz="0 -0.03 0.004" rpy="0 0 0"/>
        </joint>

        <joint name="ired1_joint" type="fixed">
            <parent link="d435_camera" />
            <child link="ired1" />
            <origin xyz="0 -0.06 0.004" rpy="0 0 0"/>
        </joint>

        <joint name="ired2_joint" type="fixed">
            <parent link="d435_camera" />
            <child link="ired2" />
            <origin xyz="0 0.01 0.004" rpy="0 0 0"/>
        </joint>

    </xacro:if>


    <xacro:if value="$(eval front_camera_type=='stereo')">

      <!-- STEREO CAMERA PLATE -->

      <link name="front_stereo_camera_plate">

        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
              <box size="0.02 0.1 0.02"/>
            </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
              <box size="0.02 0.1 0.02"/>
            </geometry>
            <material name="black"/>
        </visual>

        <inertial>
            <mass value="0.01"/>
            <xacro:box_inertia m="0.01" x="0.02" y="0.1" z = "0.02"/>
        </inertial>
  
      </link>
  
      <joint name="front_stereo_camera_plate_joint" type="fixed">
          <origin rpy="0 0 0" xyz="0 0 ${front_camera_height/2+0.02/2}"/>
          <parent link="front_camera_holder"/>
          <child link="front_stereo_camera_plate"/>
      </joint>
  
      <gazebo reference="front_stereo_camera_plate">
          <material>Gazebo/Black</material>
      </gazebo>

      <link name="stereo_camera_optical" />

      <joint name="stereo_camera_optical_joint" type="fixed">
        <origin rpy="${3*pi/2} ${0} ${3*pi/2}" xyz="0 0 0"/>
        <parent link="front_stereo_camera_plate"/>
        <child link="stereo_camera_optical"/>
      </joint>

      <xacro:stereo_camera dexterity="left"  lr="1"/>
      <xacro:stereo_camera dexterity="right" lr="-1"/>

    </xacro:if>

    <xacro:if value="$(eval front_camera_type=='kinect')">

      <!-- KINECT CAMERA -->

      <link name="kinect_camera">

        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
              <box size="0.07 0.3 0.09"/>
            </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 0" rpy="0 0 ${pi/2}" />
            <geometry>
              <mesh filename="package://atreus/meshes/kinect/kinect.dae"/>
            </geometry>
            <material name="black"/>
        </visual>

        <inertial>
            <mass value="0.01"/>
            <xacro:box_inertia m="0.01" x="0.07" y="0.3" z = "0.09"/>
        </inertial>
  
      </link>

      <joint name="kinect_camera_joint" type="fixed">
          <origin rpy="0 0 0" xyz="0 0 ${front_camera_height/2+0.09/2-0.01}"/>
          <parent link="front_camera_holder"/>
          <child link="kinect_camera"/>
      </joint>
  
      <link name="kinect_camera_optical"/>

      <joint name="kinect_camera_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-${pi/2} 0 -${pi/2}"/>
        <parent link="kinect_camera"/>
        <child link="kinect_camera_optical"/>
      </joint>
  
    </xacro:if>
    

</xacro:if>


<!-- ............................. SIDE CAMERAS ................................... -->

<xacro:if value="$(arg side_camera_enabled)">

    <xacro:side_camera dexterity="left"  lr="1"/>
    <xacro:side_camera dexterity="right" lr="-1"/>

</xacro:if>

<!-- ............................. ULTRASONICS .................................... -->

<xacro:if value="$(arg ultrasonic_enabled)">

    <xacro:ultrasonic_sensor face="front" dexterity="left"  lr ="1"/>
    <xacro:ultrasonic_sensor face="front" dexterity="right" lr="-1"/>

    <xacro:ultrasonic_sensor face="side"  dexterity="left"  lr ="1"/>
    <xacro:ultrasonic_sensor face="side"  dexterity="right" lr="-1"/>

</xacro:if>

<!-- ............................. 2D LIDAR ........................................ -->

<xacro:if value="$(arg two_d_lidar_enabled)">

    <link name="two_d_lidar">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
           <cylinder length="0.06" radius="0.075"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
           <cylinder length="0.06" radius="0.075"/>
          </geometry>
          <material name="orange"/>
        </visual>

        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <mass value="0.1"/>
          <xacro:cylinder_inertia m="0.1" r="0.075" h="0.06"/>
        </inertial>
   </link>

   <joint name="two_d_lidar_joint" type="fixed">
      <parent link="base_link"/>
      <child link="two_d_lidar"/>
      <origin xyz="${chassis_length/2 - 0.075} 0 ${chassis_ground_clearance + chassis_height/2 + 0.06/2}" rpy="0 0 ${-pi/2}" /> 
    </joint>

   <gazebo reference="two_d_lidar">
       <material>Gazebo/Orange</material>
   </gazebo>

</xacro:if>


<!-- ..................... OBSTACLE FEASIBILITY MODE ............................... -->

<xacro:if value="$(arg obstacle_feasibility_mode_enabled)">

  <xacro:sonar_plate_setup dexterity="left"   type="rod"   lr ="1"/>
  <xacro:sonar_plate_setup dexterity="right"  type="rod"   lr="-1"/>
  <xacro:sonar_plate_setup dexterity="centre" type="plate" lr ="0"/>

  <xacro:plate_sensors placement="psd1L" fb ="1"  lr ="1" />
  <xacro:plate_sensors placement="psd1R" fb ="1"  lr="-1" />
  <xacro:plate_sensors placement="psd2L" fb="-1"  lr ="1" />
  <xacro:plate_sensors placement="psd2R" fb="-1"  lr="-1" />

</xacro:if>


<!-- ............................................................................... -->

</robot>
