frame_id:        base_footprint
map_frame_id:    map
odom_frame_id:   odom

subscribe_depth: false
subscribe_rgb:   false
subscribe_rgbd:  true
subscribe_scan:  true

approx_sync:     true

RGBD/NeighborLinkRefining:      true
RGBD/ProximityBySpace:          true
RGBD/AngularUpdate:             0.01
RGBD/LinearUpdate:              0.01
RGBD/OptimizeFromGraphEnd:      false
RGBD/ProximityPathMaxNeighbors: 10

Grid/FromDepth: false
# Grid/3D: true

Reg/Force3DoF:  true
Reg/Strategy:   1

Icp/VoxelSize:                  0.05
Icp/MaxCorrespondenceDistance:  0.1
