base_local_planner: base_local_planner/TrajectoryPlannerROS

TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  # max_vel_x_backwards: 0.5
  max_vel_theta: 5.0
  min_in_place_vel_theta: 5.0

  acc_lim_theta: 5.0
  acc_lim_x: 0.5

  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.2

  holonomic_robot: false
  meter_scoring: true